project_id          = "cool-academy-413922"
source_image        = "centos-stream-8-v20240110"
source_image_family = "centos-stream-8"
machine_type        = "e2-standard-2"
image_name          = "assignment04-nodeapp"
ssh_username        = "packer"
zone                = "us-central1-a"
credentials_file    = "C:/Users/heman/Downloads/cool-academy-413922-37a71c361d0a.json"