name: Pull request raised
on: [pull_request]
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        # host port: 3800 # Optional, default value is 3306. The port of host
        # container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'assignment01'
        mysql root password: '123' # Required if "mysql user" is empty, default is empty. The root superuser password
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
    - name: Run `packer init`
      id: init
      run: |
        cd packer
        packer init build.pkr.hcl
    - name: Run `packer format`
      run: |
        cd packer
        packer fmt -check .
    - name: Run `packer validate`
      run: |
        cd packer
        packer validate .
