name: Integration tests
on: [pull_request]
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: 'webapp'
        mysql root password: '123'
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test